// Mocks generated by Mockito from annotations
// in dev_feed_app/test/features/posts/post_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;
import 'dart:ui' as _i14;

import 'package:dev_feed_app/src/common/patterns/result_pattern.dart' as _i8;
import 'package:dev_feed_app/src/common/services/connection_service.dart'
    as _i3;
import 'package:dev_feed_app/src/common/services/http_service.dart' as _i5;
import 'package:dev_feed_app/src/common/services/location_service.dart' as _i6;
import 'package:dev_feed_app/src/features/posts/exceptions/post_exception.dart'
    as _i10;
import 'package:dev_feed_app/src/features/posts/models/deleted_post_model.dart'
    as _i12;
import 'package:dev_feed_app/src/features/posts/models/post_model.dart' as _i9;
import 'package:dev_feed_app/src/features/posts/models/post_screen_state.dart'
    as _i2;
import 'package:dev_feed_app/src/features/posts/repositories/post_repository.dart'
    as _i7;
import 'package:dev_feed_app/src/features/posts/view_models/post_view_model.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePostScreenState_0 extends _i1.SmartFake
    implements _i2.PostScreenState {
  _FakePostScreenState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionService extends _i1.Mock implements _i3.ConnectionService {
  MockConnectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i4.Future<void> checkConnection() => (super.noSuchMethod(
    Invocation.method(#checkConnection, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);
}

/// A class which mocks [HttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpService extends _i1.Mock implements _i5.HttpService {
  MockHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> getData({
    required String? path,
  }) => (super.noSuchMethod(
    Invocation.method(#getData, [], {#path: path}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> postData({
    required String? path,
    required Map<String, dynamic>? body,
  }) => (super.noSuchMethod(
    Invocation.method(#postData, [], {#path: path, #body: body}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> putData({
    required String? path,
    required Map<String, dynamic>? body,
  }) => (super.noSuchMethod(
    Invocation.method(#putData, [], {#path: path, #body: body}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> deleteData({
    required String? path,
  }) => (super.noSuchMethod(
    Invocation.method(#deleteData, [], {#path: path}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i6.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isEnabled =>
      (super.noSuchMethod(Invocation.getter(#isEnabled), returnValue: false)
          as bool);

  @override
  _i4.Future<void> checkLocation() => (super.noSuchMethod(
    Invocation.method(#checkLocation, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.LocationPosition?> getCurrentLocation() => (super.noSuchMethod(
    Invocation.method(#getCurrentLocation, []),
    returnValue: _i4.Future<_i6.LocationPosition?>.value(),
  ) as _i4.Future<_i6.LocationPosition?>);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i7.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i8.ResultPattern<List<_i9.PostModel>, _i10.PostException>>
  findAllPosts() => (super.noSuchMethod(
    Invocation.method(#findAllPosts, []),
    returnValue:
        _i4.Future<
          _i8.ResultPattern<List<_i9.PostModel>, _i10.PostException>
        >.value(
          _i11.dummyValue<
            _i8.ResultPattern<List<_i9.PostModel>, _i10.PostException>
          >(this, Invocation.method(#findAllPosts, [])),
        ),
  ) as _i4.Future<_i8.ResultPattern<List<_i9.PostModel>, _i10.PostException>>);

  @override
  _i4.Future<_i8.ResultPattern<_i9.PostModel, _i10.PostException>> createPost({
    required String? title,
    required String? content,
  }) => (super.noSuchMethod(
    Invocation.method(#createPost, [], {#title: title, #content: content}),
    returnValue:
        _i4.Future<_i8.ResultPattern<_i9.PostModel, _i10.PostException>>.value(
          _i11.dummyValue<_i8.ResultPattern<_i9.PostModel, _i10.PostException>>(
            this,
            Invocation.method(#createPost, [], {
              #title: title,
              #content: content,
            }),
          ),
        ),
  ) as _i4.Future<_i8.ResultPattern<_i9.PostModel, _i10.PostException>>);

  @override
  _i4.Future<_i8.ResultPattern<_i9.PostModel, _i10.PostException>> updatePost({
    required int? id,
    required String? title,
    required String? content,
  }) => (super.noSuchMethod(
    Invocation.method(#updatePost, [], {
      #id: id,
      #title: title,
      #content: content,
    }),
    returnValue:
        _i4.Future<_i8.ResultPattern<_i9.PostModel, _i10.PostException>>.value(
          _i11.dummyValue<_i8.ResultPattern<_i9.PostModel, _i10.PostException>>(
            this,
            Invocation.method(#updatePost, [], {
              #id: id,
              #title: title,
              #content: content,
            }),
          ),
        ),
  ) as _i4.Future<_i8.ResultPattern<_i9.PostModel, _i10.PostException>>);

  @override
  _i4.Future<_i8.ResultPattern<_i12.DeletedPostModel, _i10.PostException>>
  deletePost(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#deletePost, [id]),
        returnValue:
            _i4.Future<
              _i8.ResultPattern<_i12.DeletedPostModel, _i10.PostException>
            >.value(
              _i11.dummyValue<
                _i8.ResultPattern<_i12.DeletedPostModel, _i10.PostException>
              >(this, Invocation.method(#deletePost, [id])),
            ),
      ) as _i4.Future<
        _i8.ResultPattern<_i12.DeletedPostModel, _i10.PostException>
      >);
}

/// A class which mocks [PostViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostViewModel extends _i1.Mock implements _i13.PostViewModel {
  MockPostViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostScreenState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _FakePostScreenState_0(this, Invocation.getter(#state)),
  ) as _i2.PostScreenState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> getAllPosts() => (super.noSuchMethod(
    Invocation.method(#getAllPosts, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> createPost({
    required String? title,
    required String? content,
  }) => (super.noSuchMethod(
    Invocation.method(#createPost, [], {#title: title, #content: content}),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePost({
    required int? id,
    required String? title,
    required String? content,
  }) => (super.noSuchMethod(
    Invocation.method(#updatePost, [], {
      #id: id,
      #title: title,
      #content: content,
    }),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> deletePost(int? id) => (super.noSuchMethod(
    Invocation.method(#deletePost, [id]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  void resetPostState() => super.noSuchMethod(
    Invocation.method(#resetPostState, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetDeletedPostState() => super.noSuchMethod(
    Invocation.method(#resetDeletedPostState, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.PostScreenState build() => (super.noSuchMethod(
    Invocation.method(#build, []),
    returnValue: _FakePostScreenState_0(this, Invocation.method(#build, [])),
  ) as _i2.PostScreenState);

  @override
  void emitState(_i2.PostScreenState? newState) => super.noSuchMethod(
    Invocation.method(#emitState, [newState]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
